{{- if .Values.inlets_use_token }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "inlets_chart.fullname" . }}-token
  labels:
    app.kubernetes.io/name: {{ include "inlets_chart.name" . }}
    helm.sh/chart: {{ include "inlets_chart.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  token: {{ .Values.inlets_token | b64enc }}
{{- end }}
